### ISSUE TITLE
What should I do if I want to make it work with Chinese Language?

### ISSUE THREAD

**Issue by BenDerPan** [facebookresearch/DrQA#29]
Will DrQA support Chinese language? If I use [Jieba](https://github.com/fxsjy/jieba) as the Tokenizer, what should I do to make it work?

**Comment by yasamyang** [comment]
I have the same question. I think the good way is writing a Jieba tokenizer for DrQA. Now I do an easy but stupid way that don't need to change the DrQA code. That is you can use Jieba to divide each text of your corpus into a sequence of tokens (separate by whitespace) first and then convert it to SQuAD format. Although the DrQA tokenizer would divide tokens again, it works. Make sure the DrQA tokenizer only divides text by whitespace, otherwise you will get empty answer. In this way, you don't need to use the pos and ner when train the reader model because preprocessing get the wrong pos and ner for Chinese tokens.

**Comment by ajfisch** [comment]
Unfortunately there are no plans on my end to support other languages (as mentioned in #24, #16, #10).

Sure, you could make your own Chinese tokenizer -- in fact it would be quite easy to add a new class in drqa/tokenizers. You can see several examples of tokenizers there (CoreNLPTokenizer, SpacyTokenizer, RegexpTokenizer,  SimpleTokenizer). And yes, you don't need to train with lemma, pos, or ner tags.

The main issue however is that you will need training data.
