### ISSUE TITLE
How to get DrQA answers in JSON format...??

### ISSUE THREAD

**Issue by Deepakchawla** [facebookresearch/DrQA#43]
Currently, I am getting answers with use `python scripts/pipeline/interactive.py` and format is something like that 
```
>>> process('What is question answering?')

Top Predictions:
+------+----------------------------------------------------------------------------------------------------------+--------------------+--------------+-----------+
| Rank |                                                  Answer                                                  |        Doc         | Answer Score | Doc Score |
+------+----------------------------------------------------------------------------------------------------------+--------------------+--------------+-----------+
|  1   | a computer science discipline within the fields of information retrieval and natural language processing | Question answering |    1917.8    |   327.89  |
+------+----------------------------------------------------------------------------------------------------------+--------------------+--------------+-----------+

Contexts:
[ Doc = Question answering ]
Question Answering (QA) is a computer science discipline within the fields of
information retrieval and natural language processing (NLP), which is
concerned with building systems that automatically answer questions posed by
humans in a natural language.
```

But it is not much use for my project.
So can anyone tell how to get the answers in JSON format or in one line which I can....

**Comment by ajfisch** [comment]
Look at the code for [interactive.py](https://github.com/facebookresearch/DrQA/blob/master/scripts/pipeline/interactive.py#L80-L82) to see how it uses the `drqa.pipeline.DrQA` API. The return of [process()](https://github.com/facebookresearch/DrQA/blob/master/drqa/pipeline/drqa.py#L288-L299.) is a dict.

So if you want to use DrQA in a project, it's probably better to import it yourself and use the functions directly (rather than parse the output of the scripts). The scripts are just to serve as an example.

**Comment by Deepakchawla** [comment]
Thanks Again @ajfisch for helping me...
