### ISSUE TITLE
Document Retriever: UnicodeDecodeError- Error and Resolution

### ISSUE THREAD

**Issue by POMCP** [facebookresearch/DrQA#52]
I am experimenting with the code to work with the German wikipedia documents on a MacBook Pro. When loading the extracted documents to the NoSQL db, I use the prep_wikipedia.py as a preprocessing routine as described. 

There was, however, an error that I keep getting: UnicodeDecodeError: the 'utf-8' codec cannot decode 0x80 at position 3131, invalid start byte. 

Although the original extracted documents are in the 'utf-8' encoding, this error therefore was misleading. On digging this up a bit more I discovered that the script build_db.py cycles through a list of directories in the data path. When this script is run on a MacBook, in addition to the list of directories in the data path, a hidden system directory .DS_Store is also returned. This was the reason of the error.

To fix this, I simply made a change to the build_db.py to ignore all the folders that startwith a '.' 
It worked then.

**Comment by eijoac** [comment]
I got a similar problem. I am on Red Hat Linux 7. I kept getting the following error no matter how simple I made that JSON file.

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 98: invalid start byte`

The JSON file is simply

`{"id": "ch1", "text": "Alice was"}`

Any idea?

**Comment by POMCP** [comment]
Wow that is another insight. Thanks for sharing. 
As I mentioned in my post, on a mac the hidden folder .DS_Store is the prevents the script from running.

**Comment by ajfisch** [comment]
I'm sorry you are having issues with the `build_db.py`. Indeed it is not robust to special files and will try to process anything that `os.walk` will return. Note that if you provide a direct file path instead of a directory path, it will open just that file.

The sqlite db is initialized before walking the source file path, so if they are in the same directory the db file will already have been created, which will cause problems.

Pull requests are welcome to making `iter_files` in `build_db.py` more suitable.
