### ISSUE TITLE
interactive.py not returning anything.

### ISSUE THREAD

**Issue by samdash** [facebookresearch/DrQA#58]
I have trying out using DrQA , which is great by the way, but not able to work it out using sample data.
i followed the steps mentioned https://github.com/facebookresearch/DrQA/tree/master/scripts/retriever
Built the TF-IDF 
python build_tfidf.py /path/to/doc/db /path/to/output/dir which generated the db-tfidf-ngram\=2-hash\=16777216-tokenizer\=simple.npz  file 

now when i execute 

python scripts/retriever/interactive.py --model /path/to/model ( db-tfidf-ngram\=2-hash\=16777216-tokenizer\=simple.npz) 

It is not working i am getting empty response. Am i missing something here ? 

>>> process('bluetooth issue',k=5)
+------+--------+-----------+
| Rank | Doc Id | Doc Score |
+------+--------+-----------+
+------+--------+-----------+

Here is my simple data with just 2 lines 
[sample.txt](https://github.com/facebookresearch/DrQA/files/1454994/sample.txt)

**Comment by ajfisch** [comment]
Hi,

This is an unfortunate side effect of the small sample data you have chosen.

For our TF-IDF ranker, we chose to use the probabilistic form of IDF with +.5 smoothing: 
```
IDF = log((N - Nt + 0.5) / (Nt + 0.5))
```
(N = number of documents, Nt = document frequency of term `t`).

In your situation, you have **2** documents, and `bluetooth` appears in **1** of them. So IDF = `log((2 - 1 + 0.5) / (1 + 0.5)) = log(1) = 0`. Since the TF-IDF score is 0, it is not retrieved.

If you switch the IDF term to say `log(1 + N / (Nt + eps))` (or something else always > 0) then it will work. It will also work if you increase the corpus size.

**Comment by samdash** [comment]
So i have to change build_tfidf.py below 2 lines 

tfidf = log(tf + 1) * log((N - Nt + 0.5) / (Nt + 0.5))  and 
idfs = np.log((cnts.shape[1] - Ns + 0.5) / (Ns + 0.5))

to something like this ? 

tfidf = log(tf + 1) * log((1+N) / (Nt))  and 
idfs = np.log((cnts.shape[1] - Ns ) / (Ns))

**Comment by ajfisch** [comment]
You don't have to change anything if you add more data. You probably won't run into the case where discriminative words appear in over half your documents.

Or change this [line](https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/build_tfidf.py#L143) to 
```
idfs = np.log(1 + cnts.shape[1] / (Ns + 0.5))
```

And this [line](https://github.com/facebookresearch/DrQA/blob/master/drqa/retriever/tfidf_doc_ranker.py#L109) to:
```
idfs = np.log(1 + self.num_docs / (Ns + 0.5))
```

**Comment by samdash** [comment]
Great it works  👍

**Comment by samdash** [comment]
Thanks Adam a lot, now that my Document Retriever is working great, i want to take it to next step.
from my sample.txt which i attached above, how can i make it SQuAD Format? for example shown in below URL
https://rajpurkar.github.io/SQuAD-explorer/explore/1.1/dev/Nikola_Tesla.html

how do i generate Questions and Answers from my corpus ( sample.txt)?
